name: ScreenSnapApp
options:
  bundleIdPrefix: com.screensnap
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: fr

targets:
  ScreenSnapApp:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - ScreenSnapApp
    info:
      path: Info.plist
      properties:
        CFBundleName: ScreenSnap
        CFBundleDisplayName: ScreenSnap
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright © 2025. All rights reserved."
        NSAppleEventsUsageDescription: "Cette app nécessite l'accès aux événements Apple pour les raccourcis clavier."
        NSScreenCaptureUsageDescription: "Cette app nécessite l'accès à la capture d'écran pour prendre des screenshots."
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.screensnap.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: ScreenSnapApp.entitlements
    entitlements:
      properties:
        com.apple.security.automation.apple-events: true
        com.apple.security.device.camera: false
        com.apple.security.personal-information.photos-library: false
        com.apple.security.cs.allow-unsigned-executable-memory: true
